### ISSUE TITLE
Required option not passed: "access_token" (Constant Contact API v3)

### ISSUE THREAD

**Issue by thewebadvisors** [chadhutchins/oauth2-constantcontact#1]
So, I've been running into issues with the sample code for this package:

```
    // Try to get an access token (using the authorization code grant)
    $token = $provider->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);
```
The redirect from CC works fine, I'm able to get a `code` and `state` value, but any attempt to get an access token fails with the following error.

```
[0] => Required option not passed: "access_token"
#0 /home/example/dev.example.com/releases/1/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(746): League\OAuth2\Client\Token\AccessToken->__construct(Array)
#1 /home/example/dev.example.com/releases/1/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(544): League\OAuth2\Client\Provider\AbstractProvider->createAccessToken(Array, Object(League\OAuth2\Client\Grant\AuthorizationCode))
#2 /home/example/dev.example.com/releases/1/app/src/Controller/ConstantContactController.php(83): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array)
```

My only thought is that the authorization headers aren't being set correctly. Any thoughts on where this is breaking down?

**Comment by chadhutchins** [comment]
Hello, I just gave mine a test and it seems to work. However I did see any issue with the scopes. I had some default scopes in there that may have been causing issues. Upgraded to 1.0.2 and try again. Let me know if that solves the issue.

Also, I would verify $_GET['code'] contains the value you are expecting.

**Comment by thewebadvisors** [comment]
So, after some hair-pulling last night and some excessive logging, it looks like the `redirect_uri` param was double-encoded: the first time when I supplied it (as per the CC examples docs), which again was encoded a second time by the core OAuth2 client.

While the initial hand-shake worked to get the first access token, I still ended up having to sub-class your provider to overload `getAuthorizationHeaders` to supply the access token in `Authorization` header for subsequent requests, e.g. 
```
    protected function getAuthorizationHeaders($token = null)
    {
        return ['Authorization' => 'Bearer ' . $token];
    }  
```
And finally, a consideration: unless I'm missing something, you may want to sub-class the `AccessToken` to expose a `setExpires` mutator since CC doesn't send back an expires value when asking for the initial auth token or refreshing an existing token (from what I can see in my testing). Granted, it may be very specific to my implementation for persisting the auth-token, but it was useful for re-hydrating an AccessToken from a db store or cache (the `hasExpired` method in the core `AcessToken` assumes you've persisted the `expires` value).

**Comment by thewebadvisors** [comment]
Closing this issue since it's not specific to your implementation—thank you for following up!

**Comment by thewebadvisors** [comment]
> ... I had some default scopes in there that may have been causing issues. Upgraded to 1.0.2 and try again. Let me know if that solves the issue.

Forgot to respond to this: yes, this was a minior issue, but overcome by suppling my own scopes

> Also, I would verify $_GET['code'] contains the value you are expecting.

The callback from CC works as expected, the value for `code` is valid.

**Comment by chadhutchins** [comment]
Thanks for the details and for closing this out!
